// ============================================
// JoogadTools — Blog Data Structure
// Add snippets generated by the Blog Editor tool here!
// ============================================

const blogPosts = [
  {
    title: "Welcome to the JoogadTools Blog",
    slug: "welcome-to-the-joogadtools-blog",
    description: "An introduction to the JoogadTools platform, our 100% client-side philosophy, and what you can expect from this brand new blog.",
    date: "2026-04-18",
    image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=800",
    tags: ["Announcement", "Platform"],
    author: "JoogadTools Team"
  }
];
